from typing import get_type_hints, Callable, Dict, Any



# Generated by Claude Sonnet 3.5
def string_to_dict(input_string):
    lines = input_string.strip().split('\n')
    result = {}
    for line in lines:
        if ':' in line:
            key, value = line.split(':', 1)
            key = key.strip()
            value = value.strip()
            result[key] = value
    
    return result

# TODO add support for enums
def build_tool_schema(f: Callable):
    """Build a JSON schema for a tool function."""
    descriptions = string_to_dict(f.__doc__)
    hints = get_type_hints(f)
    schema = {
        "type": "object",
        "properties": {},
        "required": []
    }

    for param, hint in hints.items():
        if param == "return":
            continue
        print(param, hint)
        var_type = ""
        if hint is int or hint is float:
            var_type = "number"
        if hint is str:
            var_type = "string"
        schema["properties"][param] = {
            "type": var_type,
            "description": descriptions[param]
        }
        schema["required"].append(param)
    return schema
